const ERROR_CODE = {
    INVALID_OTP: 4001,
    INVALID_SERVER_TOKEN: 4002,
    DETAIL_NOT_FOUND: 4003,
    TOKEN_EXPIRED: 4004,
    SET_PASSWORD_FAILED: 4005,
    INSUFFICIENT_BALANCE: 4006,
    SOMETHING_WENT_WRONG: 4007,
    ENGLISH_NAME_REQUIRED: 4008,
    INVALID_CAPTCHA: 4009,
    DECLINE_BY_ADMIN:4010
};

// partner CODES
const PARTNER_ERROR_CODE = {
    DETAIL_NOT_FOUND: 5001,
    PASSWORD_WRONG: 5002,
    PARTNER_NOT_APPROVE: 5003,
    PHONE_ALREADY_REGISTERED: 5004,
    EMAIL_ALREADY_REGISTERED: 5005,
    SOCIAL_ID_NOT_FOUND: 5006,
    COUNTRY_NOT_FOUND: 5007,
    VEHICLE_LIST_NOT_FOUND:5008,
    VEHICLE_NOT_FOUND : 5010
}

const ADMIN_ERROR_CODE = {
    ADD_FAILED: 4010,
    UPDATE_FAILED: 4011,
    DETAIL_NOT_FOUND: 4012,
    DELETE_FAILED: 4013,
    EMAIL_ALREADY_REGISTERED: 4014,
    NAME_ALREADY_REGISTERED: 4018,
    INVALID_USERNAME:4080,
    INVALID_PASSWORD:4081,
};

const CORPORATE_ERROR_CODE = {
    DETAIL_NOT_FOUND: 6000,
    USER_ALREADY_IN_OTHER_CORORATE: 6001,
    PASSWORD_WRONG: 6002,
    NOT_APPROVE: 6003,
    PHONE_ALREADY_REGISTERED: 6004,
    EMAIL_ALREADY_REGISTERED: 6005,
    SOCIAL_ID_NOT_FOUND: 6006,
    COUNTRY_NOT_FOUND: 6007,
}
const SERVICE_TYPE_ERROR_CODE = {
    NAME_ALREADY_REGISTERED: 4015,
}

const COUNTRY_ERROR_CODE = {
    COUNTRY_ALREADY_REGISTERED: 4016,
    BUSINESS_NOT_IN_YOUR_COUNTRY: 4017,
    COUNTRY_NOT_FOUND: 4027
}

const SETTINGS_ERROR_CODE = {
    UPDATE_FAILED: 4018,
}

const PROMO_ERROR_CODE = {
    PROMO_CODE_ALREADY_USED: 4019,
    DELETE_FAILED: 4020,
    UPDATE_FAILED: 4021,
    PROMO_CODE_DATA_ADD_FAILED: 4022,
    PROMO_CODE_DATA_NOT_FOUND: 4023,
    PROMO_CODE_WITH_SAME_NAME_ALREADY_EXISTS: 4024,
    BANNER_WITH_SAME_NAME_ALREADY_EXISTS: 4082,
    BANNER_NOT_FOUND:4083

}

const CITY_ERROR_CODE = {
    ADD_FAILED: 4023,
    DELETE_FAILED: 4024,
    UPDATE_FAILED: 4025,
    CITY_ALREADY_REGISTERED: 4026
}

const DOCUMENT_ERROR_CODE = {
    ADD_FAILED: 4028,
    DELETE_FAILED: 4029,
    UPDATE_FAILED: 4030,
    CITY_ALREADY_REGISTERED: 4031,
    DOCUMENT_NOT_UPLOADED: 4050,
    DOCUMENT_ALREADY_EXISTS: 4051
}

const PRICE_ERROR_CODE = {
    ADD_FAILED: 4032,
    DELETE_FAILED: 4033,
    UPDATE_FAILED: 4034,
    CITY_ALREADY_REGISTERED: 4035,
    ALREADY_EXISTS: 7073

}

const LIST_ERROR_CODE = {
    DETAIL_NOT_FOUND: 4036,
    DELETE_FAILED: 4037,
    UPDATE_FAILED: 4038,
    PHONE_ALREADY_REGISTERED: 4039,
    EMAIL_ALREADY_REGISTERED:4056,
    ALREADY_EXITS: 4041,
    PROVIDER_IN_TRIP: 4042,
    USER_IN_TRIP: 4043,
    TRIP_NOT_FOUND: 4044,

}

const LANGUAGE_ERROR_CODE = {
    NAME_ALREADY_REGISTERED: 4040,
    LANGUAGE_NOT_FOUND : 70001,
    INVALID_JSON_FILE: 7002
}

const TYPE_ERROR_CODE = {
    TRIP_ALREADY_RUNNING:995,
    DETAIL_NOT_FOUND: 6001,
    PASSWORD_WRONG:6002,
    INVALID_DATA:6003,
    PHONE_ALREADY_REGISTERED: 6004,
    EMAIL_ALREADY_REGISTERED: 6005,
    NOT_APPROVE: 6006,
    PROVIDER_NOT_FOUND:60000000,
}

const HUB_ERROR_CODE = {
    VEHICLE_IN_USE: 7071
}

const VEHICLE_MODEL_BRAND_ERROR_CODE = {
    ALREADY_EXITS: 7072
}

const RENT_CAR_ERROR_CODE = {
    TYPE_ALREADY_EXITS: 7081,
    BRAND_ALREADY_EXITS: 7082,
    MODEL_ALREADY_EXITS: 7083,
    FEATURE_ALREADY_EXITS: 7084,
    SPECIFICATION_ALREADY_EXITS: 7085,
    BRAND_NOT_ADDED: 7086,
    BRAND_NOT_FOUND: 7087,
    MODEL_NOT_ADDED: 7088,
    AVAILABILITY_SET_FAILED: 7089
}

module.exports = {
    ERROR_CODE,
    PARTNER_ERROR_CODE,
    ADMIN_ERROR_CODE,
    CORPORATE_ERROR_CODE,
    SERVICE_TYPE_ERROR_CODE,
    COUNTRY_ERROR_CODE,
    SETTINGS_ERROR_CODE,
    PROMO_ERROR_CODE,
    CITY_ERROR_CODE,
    DOCUMENT_ERROR_CODE,
    PRICE_ERROR_CODE,
    LIST_ERROR_CODE,
    LANGUAGE_ERROR_CODE,
    TYPE_ERROR_CODE,
    HUB_ERROR_CODE,
    VEHICLE_MODEL_BRAND_ERROR_CODE,
    RENT_CAR_ERROR_CODE
}