
const ADMIN_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2001,
    UPDATE_SUCCESSFULLY: 2002,
    LIST_SUCCESSFULLY: 2003,
    GET_DETAIL_SUCCESSFULLY: 2004,
    DELETE_SUCCESSFULLY: 2005,
    LOGIN_SUCCESSFULLY: 2006,
    LOGOUT_SUCCESSFULLY: 2007,
    LINK_SENT_SUCCESSFULLY: 2008,
    UPDATE_PASSWORD_SUCCESSFULLY: 2009
};

const PARTNER_MESSAGE_CODE = {
    LOGIN_SUCCESSFULLY: 3001,
    LOGOUT_SUCCESSFULLY: 3002,
    SEND_LINK_SUCCESSFULLY: 3003,
    UPDATE_PASSWORD_SUCCESSFULLY: 3004,
    REGISTER_SCUUCESSFULLY:3012,
    ADD_SUCCESSFULLY: 3005,
    UPDATE_SUCCESSFULLY: 3006,
    DELETE_SUCCESSFULLY: 3007,
    GET_DETAILS_SUCCESSFULLY: 3008,
    ASSIGN_VEHICLE: 3009,
    REMOVE_VEHICLE: 3010,
    BANK_ADD_SUCCESSFULLY: 3011
}

const SERVICE_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2010,
    UPDATE_SUCCESSFULLY: 2011
}

const COUNTRY_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2012,
    UPDATE_SUCCESSFULLY: 2013,
}

const SETTINGS_MESSAGE_CODE = {
    UPDATE_SUCCESSFULLY: 2014,
    SENT_SUCCESSFULLY: 2000
}

const FILE_MESSAGE_CODE = {
    UPDATE_SUCCESSFULLY: 2015
}

const PROMO_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2016,
    DELETE_SUCCESSFULLY: 2017,
    UPDATE_SUCCESSFULLY: 2018,
    BANNER_ADD_SUCCESSFULLY :2077,
    BANNER_UPDATED_SUCCESSFULLY :2078,
    BANNER_DELETED_SUCCESSFULLY :2079
}

const CITY_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2019,
    DELETE_SUCCESSFULLY: 2020,
    UPDATE_SUCCESSFULLY: 2021
}

const DOCUMENT_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2022,
    DELETE_SUCCESSFULLY: 2023,
    UPDATE_SUCCESSFULLY: 2024
}

const PRICE_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2025,
    DELETE_SUCCESSFULLY: 2026,
    UPDATE_SUCCESSFULLY: 2027,
    ALREADY_EXISTS: 2034
}

const LIST_MESSAGE_CODE = {
    DELETE_SUCCESSFULLY: 2028,
    UPDATE_SUCCESSFULLY: 2029,
    ADD_SUCCESSFULLY: 2032,
    ALREADY_EXISTS: 2035,
    APRROVED_SUCCESSFULLY: 2036,
    DECLINE_SUCCESSFULLY: 2037,
    UNFREEZE_SUCCESSFULLY: 2038,
    ADD_VEHICLE_SUCCESSFULLY: 2039,
}

const LANG_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2031,
    LANGUAGE_DELETED_SUCCESSFULLY : 7000,
}

const TYPE_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 5001,
    UPDATE_SUCCESSFULLY: 5002,
    LIST_SUCCESSFULLY: 5003,
    GET_DETAIL_SUCCESSFULLY: 5004,
    DELETE_SUCCESSFULLY: 5005,
    LOGIN_SUCCESSFULLY: 5006,
    LOGOUT_SUCCESSFULLY: 5008,
    LINK_SENT_SUCCESSFULLY: 5009,
    UPDATE_PASSWORD_SUCCESSFULLY: 5010,
    SEND_REQUEST_SUCCESSFULLY : 5011
};

const CANCELLATION_REASON = {
    ADD_SUCCESSFULLY: 6001,
    UPDATE_SUCCESSFULLY : 6002,
    DELETE_SUCCESSFULLY : 6003,
}

const VEHICLE_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2070,
    UPDATE_SUCCESSFULLY: 2071,
    ASSIGNED_SUCCESSFULLY: 2072,
    UNASSIGNED_SUCCESSFULLY: 2073
}

const HUB_USER_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2074,
    UPDATE_SUCCESSFULLY: 2075,
    DELETED_SUCCESSFULLY: 2076
}


const VEHICLE_MODEL_BRAND_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2049,
    UPDATE_SUCCESSFULLY: 2050
}

const CAR_RENT_MESSAGE_CODE = {
    ADD_SUCCESSFULLY: 2081,
    UPDATE_SUCCESSFULLY: 2082,
    BRAND_ADD_SUCCESSFULLY: 2083,
    BRAND_UPDATE_SUCCESSFULLY: 2084,
    MODEL_ADD_SUCCESSFULLY: 2085,
    MODEL_UPDATE_SUCCESSFULLY: 2086,
    FEATURE_ADDED_SUCCESSFULLY: 2087,
    FEATURE_UPDATE_SUCCESSFULLY: 2088,
    SPECIFICATION_ADDED_SUCCESSFULLY: 2089,
    SPECIFICATION_UPDATE_SUCCESSFULLY: 2090,
    VEHICLE_APPROVED_SUCCESSFULLY: 2091,
    VEHICLE_REJECTED_SUCCESSFULLY: 2092,
    AVAILABILITY_SET_SUCCCESSFULLY: 2093,
    AVAILABILITY_DELETE_SUCCCESSFULLY: 2094,
    ADD_FAVOURITE_RENT_VEHICLE_SUCCESSFULLY: 2095,
    REMOVE_FAVOURITE_RENT_VEHICLE_SUCCESSFULLY: 2096,
}

module.exports = {
    ADMIN_MESSAGE_CODE,
    PARTNER_MESSAGE_CODE,
    SERVICE_MESSAGE_CODE,
    COUNTRY_MESSAGE_CODE,
    SETTINGS_MESSAGE_CODE,
    FILE_MESSAGE_CODE,
    PROMO_MESSAGE_CODE,
    CITY_MESSAGE_CODE,
    DOCUMENT_MESSAGE_CODE,
    PRICE_MESSAGE_CODE,
    LIST_MESSAGE_CODE,
    LANG_MESSAGE_CODE,
    TYPE_MESSAGE_CODE,
    CANCELLATION_REASON,
    VEHICLE_MESSAGE_CODE,
    HUB_USER_MESSAGE_CODE,
    VEHICLE_MODEL_BRAND_MESSAGE_CODE,
    CAR_RENT_MESSAGE_CODE
}