const TRIP_LIST = {
    RUNNING_TRIP:1,
    SCHEDULED_TRIP:2,
    COMPLETED_TRIP:3,
    CANCELLED_TRIP:4,
    EARNING_TRIP :5,
    DAILY_EARNING :6,
    WEEKLY_EARNING :7,
    PARTNER_WEEKLY_EARNING :8,
    USER_HISTORY : 9,
    PROVIDER_WEEKLY_EARNING : 10,
    PROVIDER_HISTORY : 11,
    COMPLETED_TRIP_OF_PARTNER : 12,
    RUNNING_TRIP_OF_PARTNER : 13,
    COMPLETED_TRIP_OF_CORPORATE:14,
    COMPLETED_TRIP_OF_DISPATCHER:15,
    COMPLETED_TRIP_OF_HOTEL:16,
    WALLET_HISTORY :18,
    SCHEDULED_TRIP_OF_PARTNER:19,
    OPEN_RIDE_RUNNING_TRIP:20,
    OPEN_RIDE_SCHEDULED_TRIP:21,
    OPEN_RIDE_COMPLETED_TRIP:22,
    OPEN_RIDE_CANCELLED_TRIP:23,
    OPEN_RIDE_REPORT:24,
    RENTAL_RUNNING_REQUEST: 25,
	RENTAL_COMPLETED_REQUEST: 26,
	RENTAL_CANCELLED_REQUEST: 27,
	RENTAL_REQUEST_REPORT: 28,
    RENTAL_TRIP_EARNING: 29
}
const EXPORT_TYPE = {
    EARNING_EXPORT:1,
}
const EXPORT_HISTORY_STATUS = {
    QUEUED: 0,
    COMPLETED: 1,
    FAILED: 2
}
const PROVIDER_STATUS = {
    WAITING: 0,
    ACCEPTED: 1,
    COMING: 2,
    ARRIVED: 4,
    TRIP_STARTED: 6,
    TRIP_COMPLETED: 9
};

const COLLECTION = {
    MASS_NOTIFICATION: 14,
    WALLET_HISTORY: 15,
    TRANSFER_HISTORY: 16,
}

// Rental Trip Status
const RENTAL_TRIP_STATUS = {
    CREATED: 0,
    ACCEPTED: 1,
    PAYMENT: 2,
    DRIVER_HANDOVER: 3,
    USER_HANDOVER: 4,
    ADDITIONAL_PAYMENT: 5,
    COMPLETED: 6,
    CANCELLED: 7
};

module.exports = {
    TRIP_LIST,
    EXPORT_TYPE,
    EXPORT_HISTORY_STATUS,
    PROVIDER_STATUS,
    COLLECTION,
    RENTAL_TRIP_STATUS
}