let mongoose = require('mongoose');
let Schema = mongoose.Schema;

module.exports = mongoose.model('Settings', new Schema({
    provider_timeout: {type: Number, default: 60},
    countryname: {type: String, default: ""},
    adminCurrencyCode: {type: String, default: ""},
    adminCurrency: {type: String, default: ""},
    adminTimeZone: {type: String, default: ""},
    sms_notification: {type: Boolean, default: false},
    email_notification: {type: Boolean, default: false},
    push_notification: {type: Boolean, default: true},
    get_referral_profit_on_card_payment: {type: Boolean, default: false},
    get_referral_profit_on_cash_payment: {type: Boolean, default: false},
    userEmailVerification: {type: Boolean, default: false},
    providerEmailVerification: {type: Boolean, default: false},
    userSms: {type: Boolean, default: false},
    providerSms: {type: Boolean, default: false},
    admin_phone: {type: String, default: ""},
    contactUsEmail: {type: String, default: ""},
    twilio_call_masking: {type: Boolean, default: false},
    access_key_id: {type: String, default: ""},
    secret_key_id: {type: String, default: ""},
    aws_bucket_name: {type: String, default: ""},
    is_use_aws_bucket: {type: Boolean, default: false},
    image_base_url: {type: String, default: ""},
    
    payments_base_url: {type: String, default: "http://localhost:5002/payments"},
    api_base_url: {type: String, default: "http://localhost:5000"},
    history_base_url: {type: String, default: "http://localhost:5001/history"},
    mass_notification_base_url: {type: String, default: ""},
    

    is_ride_share: {type: Boolean, default: false},
    is_split_payment: {type: Boolean, default: false},
    max_split_user: {type: Number, default: 5},

    admin_email: {type: String, default: ""},
    default_Search_radious: {type: Number, default: 5},
    scheduled_request_pre_start_minute: {type: Number, default: 30},
    number_of_try_for_scheduled_request: {type: Number, default: 10},
    is_public_demo: {type: Boolean, default: false},
    is_provider_initiate_trip: {type: Boolean, default: false},
    stripe_secret_key: {type: String, default: ""},
    stripe_publishable_key: {type: String, default: ""},
    paystack_secret_key: {type: String, default: ""},
    paystack_publishable_key: {type: String, default: ""},
    payu_key: {type: String, default: ""},
    payu_salt: {type: String, default: ""},
    payment_gateway_type: {type: Number, default: 10},
    paytabs_server_key: {type: String, default: ""},
    paytabs_client_key: {type: String, default: ""},
    paytabs_profileId: {type: String, default: ""},

    paypal_client_id:{type: String, default: ""},
    paypal_secret_key:{type: String, default: ""},
    paypal_environment:{type: String, default: ""},

    razorpay_client_id:{type: String, default: ""},
    razorpay_secret_key:{type: String, default: ""},
    
    email: {type: String, default: ""},
    password: {type: String, default: ""},
    domain: {type: String},
    provider_offline_min: {type: Number, default: 30},
    smtp_host: {type: String, default: ''},
    smtp_port: {type: String, default: ''},

    is_show_estimation_in_provider_app: {type: Boolean, default: false},
    is_show_estimation_in_user_app: {type: Boolean, default: false},
    is_show_user_details_in_provider_app: {type: Boolean, default: false},

    twilio_account_sid: {type: String, default: ""},
    twilio_auth_token: {type: String, default: ""},
    twilio_number: {type: String, default: ""},
    twiml_url: {type: String, default: ""},
    userPath: {type: Boolean, default: false},
    providerPath: {type: Boolean, default: false},
    android_client_app_url: {type: String, default: ""},
    android_driver_app_url: {type: String, default: ""},
    ios_client_app_url: {type: String, default: ""},
    ios_driver_app_url: {type: String, default: ""},
    find_nearest_driver_type: {type: Number, default: 1},
    request_send_to_no_of_providers: {type: Number, default: 2},
    android_user_app_gcm_key: {type: String, default: ""},
    android_provider_app_gcm_key: {type: String, default: ""},
    android_user_app_google_key: {type: String, default: ""},
    android_provider_app_google_key: {type: String, default: ""},
    ios_user_app_google_key: {type: String, default: ""},
    ios_provider_app_google_key: {type: String, default: ""},
    web_app_google_key: {type: String, default: ""},
    road_api_google_key: {type: String, default: ""},
    user_passphrase: {type: String, default: ""},
    provider_passphrase: {type: String, default: ""},
    ios_certificate_mode: {type: String, default: "sandbox"},
    hotline_app_id: {type: String, default: ""},
    hotline_app_key: {type: String, default: ""},
    google_map_lic_key: {type: String, default: ""},
    is_google_map_lic_key_expired: {type: Number, default: 0},
    server_url: {type: String, default: ""},
    app_name: {type: String, default: "OnPoint"},
    partner_panel_name: {type: String, default: "Partner Panel"},
    dispatcher_panel_name: {type: String, default: "Dispatcher Panel"},
    hotel_panel_name: {type: String, default: "Hotel Panel"},
    corporate_panel_name: {type: String, default: "Corporate Panel"},
    is_tip: {type: Boolean, default: false},
    is_toll: {type: Boolean, default: false},
    timezone_for_display_date: {type: String, default: "Asia/Kolkata"},
    android_user_app_version_code: {type: String, default: "1.0.0"},
    android_user_app_force_update: {type: Boolean, default: false},
    android_provider_app_version_code: {type: String, default: "1.0.0"},
    android_provider_app_force_update: {type: Boolean, default: false},
    ios_user_app_version_code: {type: String, default: "1.0.0"},
    ios_user_app_force_update: {type: Boolean, default: false},
    ios_provider_app_version_code: {type: String, default: "1.0.0"},
    ios_provider_app_force_update: {type: Boolean, default: false},
    is_debug_log : {type:Boolean , default : true},
    location: {type: [Number], index1: '2d'},
    firebase_apiKey: {type: String, default: ""},
    firebase_authDomain: {type: String, default: ""},
    firebase_databaseURL: {type: String, default: ""},
    firebase_projectId: {type: String, default: ""},
    firebase_storageBucket: {type: String, default: ""},
    firebase_messagingSenderId: {type: String, default: ""},
    user_panel_url: {type: String, default: ""},
    driver_panel_url: {type: String, default: ""},


    user_terms_and_condition: {type: String, default: ''},
    provider_terms_and_condition: {type: String, default: ''},
    user_privacy_policy:  {type: String, default: ''},
    user_delete_policy:  {type: String, default: ''},
    provider_privacy_policy:  {type: String, default: ''},
    provider_delete_policy:  {type: String, default: ''},
	
	android_places_autocomplete_key: {type: String, default: ""},
	ios_places_autocomplete_key: {type: String, default: ""},


	team_id: {type: String, default: ""},
	key_id: {type: String, default: ""},
	provider_bundle_id: {type: String, default: ""},
	user_bundle_id: {type: String, default: ""},
    // added for firebase security
    type: {type: String, default: ""},
    private_key_id: {type: String, default: ""},
    private_key: {type: String, default: ""},
    client_email: {type: String, default: ""},
    client_id: {type: String, default: ""},
    auth_uri: {type: String, default: ""},
    token_uri: {type: String, default: ""},
    auth_provider_x509_cert_url: {type: String, default: ""},
    client_x509_cert_url: {type: String, default: ""},
    is_user_social_login: {type: Boolean, default: true},
    is_provider_social_login: {type: Boolean, default: true},
    is_user_login_using_otp: {type: Boolean, default: true},
    is_provider_login_using_otp: {type: Boolean, default: true},
    is_guest_token: {type: Boolean, default: false},
    active_guest_token: {type: String, default: ""},
    is_otp_verification_start_trip: {type: Boolean, default: false},
    is_receive_new_request_near_destination: {type: Boolean, default: false},
    near_destination_radius: {type: Number, default: 2000},
    
    is_driver_go_home: {type: Boolean, default: false},
    is_driver_go_home_change_address: {type: Boolean, default: false},
    driver_go_home_radius: {type: Number, default: 2000},

    is_allow_multiple_stop: {type: Boolean, default: false},
    is_multiple_stop_waiting_free_on_each_stop: {type: Boolean, default: false},
    multiple_stop_count: {type: Number, default: 3},

    is_allow_ride_share: { type: Boolean, default: false },
    ride_share_pickup_radius: { type: Number, default: 3 },
    ride_share_destination_radius: { type: Number, default: 3 },

    minimum_phone_number_length: {type: Number, default: 8},
    maximum_phone_number_length: {type: Number, default: 14},

    is_production:{type: Boolean, default: false},

    webpush_public_key:{type:String,default:''},
    webpush_private_key:{type:String,default:''},
    decimal_point_value:{type:Number,default:0},

    
    is_allow_biometric_verification_for_driver: { type: Boolean, default: false },

    whatsapp_base_url:{type:String,default:''},
    is_whatsapp_authenticated:{type: Boolean, default: false},
    whatsapp_status:{type:String,default:''},
    whatsapp_qrcode:{type:String,default:''},
    is_use_captcha:{type: Boolean, default: false},
    recaptcha_site_key_for_web:{type:String,default:''},
    recaptcha_secret_key_for_web:{type:String,default:''},
    recaptcha_secret_key_for_android:{type:String,default:''},
    recaptcha_site_key_for_android:{type:String,default:''},
    recaptcha_secret_key_for_ios:{type:String,default:''},
    recaptcha_site_key_for_ios:{type:String,default:''},

    android_user_app_google_map_key:{type:String,default:''},
    android_user_app_google_places_autocomplete_key:{type:String,default:''},
    android_user_app_google_geocoding_key:{type:String,default:''},
    android_user_app_google_distance_matrix_key:{type:String,default:''},
    android_user_app_google_direction_matrix_key:{type:String,default:''},
    
    ios_user_app_google_map_key:{type:String,default:''},
    ios_user_app_google_places_autocomplete_key:{type:String,default:''},
    ios_user_app_google_geocoding_key:{type:String,default:''},
    ios_user_app_google_distance_matrix_key:{type:String,default:''},
    ios_user_app_google_direction_matrix_key:{type:String,default:''},
    
    android_driver_app_google_map_key:{type:String,default:''},
    android_driver_app_google_places_autocomplete_key:{type:String,default:''},
    android_driver_app_google_geocoding_key:{type:String,default:''},
    android_driver_app_google_distance_matrix_key:{type:String,default:''},
    android_driver_app_google_direction_matrix_key:{type:String,default:''},

    ios_driver_app_google_map_key:{type:String,default:''},
    ios_driver_app_google_places_autocomplete_key:{type:String,default:''},
    ios_driver_app_google_geocoding_key:{type:String,default:''},
    ios_driver_app_google_distance_matrix_key:{type:String,default:''},
    ios_driver_app_google_direction_matrix_key:{type:String,default:''},


    admin_panel_google_key:{type:String,default:''},
    user_panel_google_key:{type:String,default:''},
    driver_panel_google_key:{type:String,default:''},
    dispatcher_panel_google_key:{type:String,default:''},
    corporate_panel_google_key:{type:String,default:''},
    hotel_panel_google_key:{type:String,default:''},
    partner_panel_google_key:{type:String,default:''},

    flutter_user_app_google_places_autocomplete_key:{type:String,default:''},
    flutter_driver_app_google_places_autocomplete_key:{type:String,default:''},
    
    activity_logs: {type: Boolean, default: false}, // If true then it will store detailed errors with stack in ./log_files/error_log.json file
    encrypt_response: {type: Boolean, default: false},
},{
    strict: true,
    timestamps: {
        createdAt: 'created_at',
        updatedAt: 'updated_at'
    }
})
);

